# Generated by Django 3.2 on 2021-06-27 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_booker', '0002_auto_20210622_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='advance_booking',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='max_guest',
        ),
    ]
